### ISSUE TITLE
There are no install instructions

### ISSUE THREAD

**Issue by aarcro** [buildbot/buildbot_travis#11]
This looks great, but I'm brand new to buildbot, and this doesn't describe how to get your project configured in buildbot.

**Comment by smarr** [comment]
I also failed to get things to work.

The example directory gets me a working buildbot, but projects aren't saved.
Also, it seems to example is not up to date. The requirements.txt might need `buildbot_pkg==0.9.0b9`.

Is a MySQL database necessary? I'd just like an easy way to setup projects on buildbot, but use it as normal. I also don't need any of the docker functionality. Just executing the travis file on a slave would be sufficient.

**Comment by tardyp** [comment]
There is no a quick start paragraph in the README file
