### ISSUE TITLE
revive the project into buildbot nine

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot_travis#4]
Hi,

I would like to revive this project for inclusion into buildbot nine.
Nine as support for dynamic buildfactory, and better support for trigger steps, which should make a TravisBuilderFactory quite easy to write.

**Comment by tardyp** [comment]
@Jc2k during last buildbot weekly meeting, we decided, to take buildbot_travis under the buildbot group umbrella: https://github.com/buildbot/buildbot_travis

I understand from our previous discussions that you are happy with this.

Google still thinks that this is the main repository for buildbot_travis, and this has been confusing for people (especially as there is a disclaimer at the end of the readme discouraging people from using it).

Could you add a URL to our repository in order to make it more clear that further development can be done in our org repository?

**Comment by Jc2k** [comment]
Yes i'm super happy for someone to pick up my idea and run with it, and
just sad I don't have any free time at the moment to join in. I think the
best way to do this in GitHub is if its not too late I could 'transfer' my
copy into the buildbot org - that would setup a redirect in github to the
buildbot copy and you can re-push your changes. Later on if I get some free
time and decide to contribute i'd just set up a fork as normal and it would
be clear its not the master copy. I have popped onto IRC if you want to do
this in the next couple of hours - nick is Jc2k as per github.

**Comment by tardyp** [comment]
done! we can close now :)

**Comment by Jc2k** [comment]
Hurray 🎉
