### ISSUE TITLE
Waterfall and console plugins support?

### ISSUE THREAD

**Issue by bendikro** [buildbot/buildbot_travis#41]
I can't find a way to configure these plugins. Have I missed something here? Manually hacking the configurator to add these to `self.config['www']` seems to work, but maybe they don't show correct data?

**Comment by tardyp** [comment]
These plugins are not very well adapted to the buildbot_travis workflow.

Indeed you can customize anything inside the master.cfg.

see for example: https://nine.buildbot.net/#/waterfall
https://github.com/buildbot/metabbotcfg/tree/nine

**Comment by bendikro** [comment]
Ah, I see. Thanks.

**Comment by tardyp** [comment]
Now plugins are automatically configured if installed
