### ISSUE TITLE
allow arbitrary images

### ISSUE THREAD

**Issue by ddavidebor** [buildbot/buildbot_travis#66]
it would be really really nice if buidbot_travis allowed arbitrary docker images to be used, in a way similar to what wercker-ci and drone-ci allow.

This could be implemented separately by the language tag with a "box" tag,

What do you think about it?

**Comment by seankelly** [comment]
I do this by using a renderer for the image.

**Comment by ddavidebor** [comment]
@seankelly do you have an example you can share ?

**Comment by seankelly** [comment]
With #62, properties are set for `os`, `dist`, and `language`. I use OpenStackLatentWorker, so something like:
```
c['workers'].append(worker.OpenStackLatentWorker(
    ...
    block_devices=[
        {'uuid': travis_image,
        'volume_size': 10}])
))

@util.renderer
def travis_image(props):
    ...
```

With the extra properties available, I can make a decision on which image to use based on the dist and language.

**Comment by ddavidebor** [comment]
Mmmh, got it.

I'm still interested in a discussion for this to be implemented in a way that supports the usability intended for buildbot_travis. 

What I'm referring to, the "box" field, is useful only when using docker.

**Comment by tardyp** [comment]
you can use following:

```%(prop:docker-image:-buildbot/buildbot-worker)s```

in docker image configuration

![image](https://user-images.githubusercontent.com/109859/30031531-2fb3315c-9192-11e7-9172-e2f771237da3.png)

Note that It actually didn't work before #65
