### ISSUE TITLE
Working with other languages

### ISSUE THREAD

**Issue by maleadt** [buildbot/buildbot_travis#84]
I'm confused how to use buildbot_travis with other, non-Python languages. The README only vaguely mentions:

> The list of supported language is depending on your build worker configuration.

Say I have a `.bbtravis.yml` with:

```
language: julia
julia:
  - 0.6
```

(1) How do I make subsequent steps tie into this?

Also, with such a bare-bones config, I get a `julia $PROJECT python:python2.6` virtual builder thanks to https://github.com/buildbot/buildbot_travis/blob/433be92547825ace4cc4769126f2de409fe00bc3/buildbot_travis/travisyml.py#L188-L191

(2) Can I customize this, or does this need something like #62?

**Comment by seankelly** [comment]
You can customize that code, which is what #62 makes easier to do.
